sudo: required
services:
    - docker 
before_install:
    - docker build -t alfredhawkman/docker-react -f Dockerfile.dev .

script:
    - docker run alfredhawkman/docker-react npm run test -- --coverage
    